name: Build and Deploy Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.13
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Run docker compose for testing
      - uses: hoverkraft-tech/compose-action@4894d2492015c1774ee5a13a95b1072093087ec3 # v2.5.0
        with:
          compose-file: "./compose.test.yml"
          down-flags: "--rmi all"
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          URI: ${{ secrets.TEST_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ vars.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}
      - name: Execute tests in the running services
        run: docker compose exec test_fastapi_app pytest
      